Repository Sigmarik/graphics-engine, pull requests merged in 2024-05, with the labels that each got.

#24 Scene blueprints
  assets/levels/pool_table.level.xml
  assets/models/debug/debug_box.obj
  blender/level_exporter.py
  blender/model_transformer.py
  lib.flist
  lib/geometry/transforms.cpp
  lib/geometry/transforms.h
  lib/graphics/importers/materials.cpp
  lib/graphics/importers/models.cpp
  lib/graphics/objects/point_light.cpp
  lib/graphics/objects/scene.cpp
  lib/graphics/objects/scene.h
  lib/logger/logger.cpp
  lib/logger/logger.h
  lib/logics/blueprints/component_factory.hpp
  lib/logics/blueprints/component_importer.h
  lib/logics/blueprints/external_level.cpp
  lib/logics/blueprints/external_level.h
  lib/logics/blueprints/scene_importer.cpp
  lib/logics/components/logical/component_pack.cpp
  lib/logics/components/logical/component_pack.h
  lib/logics/components/physical/box_collider_importer.cpp
  lib/logics/components/physical/static_box_collider.cpp
  lib/logics/components/physical/static_box_collider.h
  lib/logics/components/visual/ambient_light_cmp.cpp
  lib/logics/components/visual/ambient_light_cmp.h
  lib/logics/components/visual/ambient_light_importer.cpp
  lib/logics/components/visual/point_light_cmp.cpp
  lib/logics/components/visual/point_light_cmp.h
  lib/logics/components/visual/point_light_importer.cpp
  lib/logics/components/visual/static_mesh.cpp
  lib/logics/components/visual/static_mesh.h
  lib/logics/components/visual/static_mesh_importer.cpp
  lib/logics/scene.cpp
  lib/logics/scene.h
  lib/logics/scene_component.cpp
  lib/logics/scene_component.h
  lib/logics/subcomponent.hpp
  lib/managers/_am_request.hpp
  lib/managers/asset_manager.cpp
  lib/managers/asset_manager.h
  lib/physics/collider.cpp
  lib/physics/constants.h
  lib/physics/objects/bouncy_object.cpp
  lib/physics/objects/bouncy_object.h
  lib/xml/data_extractors.cpp
  lib/xml/data_extractors.h
  src.flist
  src/components/pool/ball.cpp
  src/components/pool/ball.h
  src/components/pool/ball_importer.cpp
  src/components/pool/player_ball.cpp
  src/components/pool/player_ball.h
  src/main.cpp
  src/scenes/pool_game.cpp
  src/scenes/pool_game.h
Labels: logics, feature, assets

#25 Advanced window subtitles (alternative implementation)
  lib/managers/window_manager.cpp
  lib/managers/window_manager.h
  src/main.cpp
Labels: feature

#14 Active window in input controller and bug fixes
  lib.flist
  lib/input/input_controller.cpp
  lib/managers/window_manager.cpp
  lib/managers/window_manager.h
  src/main.cpp
Labels: bug, feature
